version: "3.9"
name: central-clipboard
services:
    frontend:
        build: .
        container_name: clipboard-ui
        ports:
            - "2005:3000"
        environment:
            REDIS_HOST: clipboard-redis
            REDIS_PORT: 6379
        restart: unless-stopped
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: clipboard-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data: {}
