import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/Provider";
import { AuthProvider } from "@/components/AuthProvider";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = localFont({
  src: "./(frontend)/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./(frontend)/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Centralized Clipboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Provider>
              <Navbar />
              <main className='flex-1'>{children}</main>
            </Provider>
          </AuthProvider>
        </ThemeProvider>
        <Toaster
          toastOptions={{
            className: "",
            duration: 5000,
            style: {
              background: "#0f0f0f",
              color: "#fff",
            },
            success: {
              duration: 3000,
              //@ts-ignore
              theme: {
                primary: "green",
                secondary: "black",
              },
            },
          }}
          position='bottom-right'
        />
      </body>
    </html>
  );
}
