import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/Provider";
import AppwriteTest from "@/components/test/AppwriteTest";
import { AuthProvider } from "@/lib/context/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Centralized Clipboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/* <AppwriteTest /> */}
        <AuthProvider>
          <Provider>{children}</Provider>
        </AuthProvider>
        <Toaster
          toastOptions={{
            // Define default options
            className: "",
            duration: 5000,
            style: {
              background: "#0f0f0f",
              color: "#fff",
            },

            success: {
              duration: 3000,
              //@ts-ignore
              theme: {
                primary: "green",
                secondary: "black",
              },
            },
          }}
          position='bottom-right'
        />
      </body>
    </html>
  );
}
